// <auto-generated />
namespace Finance.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class add_CostRequirementInvoiceReceived_InvoiceReceived02 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_CostRequirementInvoiceReceived_InvoiceReceived02));
        
        string IMigrationMetadata.Id
        {
            get { return "201912161032123_add_CostRequirementInvoiceReceived_InvoiceReceived02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
