// <auto-generated />
namespace Finance.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class UserAddIsRemoved01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserAddIsRemoved01));
        
        string IMigrationMetadata.Id
        {
            get { return "201912190738115_UserAddIsRemoved01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
